ALTER TABLE userdata
  ADD COLUMN IF NOT EXISTS home_base_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS home_base_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS home_base_label TEXT,
  ADD COLUMN IF NOT EXISTS home_base_source TEXT,
  ADD COLUMN IF NOT EXISTS travel_radius_km INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS travel_mode TEXT NOT NULL DEFAULT 'transit',
  ADD COLUMN IF NOT EXISTS timezone TEXT;
