const AUTHORITY_STATUS = Object.freeze({
  CONTRACT_GROUNDED: "contract_grounded",
  OUTCOME_NOT_FULLY_SPECIFIED: "outcome_not_fully_specified",
});

export const FILENAME_FIXTURE_POLICIES = Object.freeze(["allow", "normalize", "block"]);
export const FILENAME_FIXTURE_DECISION_STATUSES = Object.freeze([
  "contract_grounded",
  "owner_decision_required",
]);
export const FILENAME_FIXTURE_CORPUS_STATUSES = Object.freeze(["corpus_only"]);

export const FILENAME_FIXTURE_CATEGORIES = Object.freeze([
  "application_generated_safe_filename",
  "path_traversal",
  "path_separator",
  "control_character",
  "bidi_control",
  "empty_sanitized_filename",
  "reserved_device_name",
  "dangerous_extension_mismatch",
  "unicode_normalization_question",
  "punctuation_spacing_question",
  "content_disposition_header_safety_question",
  "drive_path_question",
  "reserved_name_variant_question",
  "extension_pattern_question",
]);

export const FILENAME_FIXTURE_AUTHORITY_MAP = Object.freeze({
  "BACKEND_CONTRACT.VAL_STO_004.PATH_TRAVERSAL": Object.freeze({
    source_document: "Backend Contract",
    section_or_validator_key: "VAL-STO-004 path traversal",
    requirement_summary: "Filename validation blocks malicious basename traversal such as parent-directory traversal.",
    supported_expected_policy: "block",
    supported_expected_category: "path_traversal",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "BACKEND_CONTRACT.VAL_STO_004.SLASH_BACKSLASH": Object.freeze({
    source_document: "Backend Contract",
    section_or_validator_key: "VAL-STO-004 path and separator rejection",
    requirement_summary: "Filename validation blocks slash and backslash separators rather than accepting caller paths.",
    supported_expected_policy: "block",
    supported_expected_category: "path_separator",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "BACKEND_CONTRACT.VAL_STO_004.CONTROL_CHARACTERS": Object.freeze({
    source_document: "Backend Contract",
    section_or_validator_key: "VAL-STO-004 control-character rejection",
    requirement_summary: "Filename validation blocks NUL, C0 controls, and C1 controls.",
    supported_expected_policy: "block",
    supported_expected_category: "control_character",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "BACKEND_CONTRACT.VAL_STO_004.RESERVED_DEVICE_NAMES": Object.freeze({
    source_document: "Backend Contract",
    section_or_validator_key: "VAL-STO-004 reserved-name rejection",
    requirement_summary: "Filename validation blocks explicitly reserved device-name basenames.",
    supported_expected_policy: "block",
    supported_expected_category: "reserved_device_name",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "BACKEND_CONTRACT.VAL_STO_004.DANGEROUS_EXTENSION_MISMATCH": Object.freeze({
    source_document: "Backend Contract",
    section_or_validator_key: "VAL-STO-004 dangerous extension mismatch",
    requirement_summary: "Filename validation blocks a permitted-looking basename ending in a prohibited executable or script extension.",
    supported_expected_policy: "block",
    supported_expected_category: "dangerous_extension_mismatch",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "BACKEND_CONTRACT.VAL_STO_004.EMPTY_SANITIZED_FILENAME": Object.freeze({
    source_document: "Backend Contract",
    section_or_validator_key: "safe_filename 1-181 characters; VAL-STO-004 safe_filename",
    requirement_summary: "A safe filename must have at least one character after the application safe-filename rule is applied.",
    supported_expected_policy: "block",
    supported_expected_category: "empty_sanitized_filename",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "EXECPLAN.P0_05.APPLICATION_GENERATED_SAFE_FILENAME": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: application-generated safe filename",
    requirement_summary: "P0-05 requires an application-generated safe filename; a simple safe ASCII basename is accepted by the corpus answer key.",
    supported_expected_policy: "allow",
    supported_expected_category: "application_generated_safe_filename",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "EXECPLAN.P0_05.UNICODE_NORMALIZATION": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: Unicode normalization",
    requirement_summary: "P0-05 requires Unicode normalization but does not specify whether non-NFC input is normalized and accepted or rejected.",
    supported_expected_policy: null,
    supported_expected_category: "unicode_normalization_question",
    authority_status: AUTHORITY_STATUS.OUTCOME_NOT_FULLY_SPECIFIED,
  }),
  "EXECPLAN.P0_05.BIDI_REJECTION": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: bidi and control-character rejection",
    requirement_summary: "P0-05 requires rejection of Unicode bidi controls in filenames.",
    supported_expected_policy: "block",
    supported_expected_category: "bidi_control",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "EXECPLAN.P0_05.PATH_SEPARATOR_REJECTION": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: path and separator rejection",
    requirement_summary: "P0-05 requires path and separator rejection but does not specify drive-style path forms without separators.",
    supported_expected_policy: null,
    supported_expected_category: "drive_path_question",
    authority_status: AUTHORITY_STATUS.OUTCOME_NOT_FULLY_SPECIFIED,
  }),
  "EXECPLAN.P0_05.RESERVED_NAME_REJECTION": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: reserved-name rejection",
    requirement_summary: "P0-05 requires reserved-name rejection but does not specify casing, extension, or trailing-character variant semantics.",
    supported_expected_policy: null,
    supported_expected_category: "reserved_name_variant_question",
    authority_status: AUTHORITY_STATUS.OUTCOME_NOT_FULLY_SPECIFIED,
  }),
  "EXECPLAN.P0_05.CONTENT_DISPOSITION_SAFETY": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: Content-Disposition safety",
    requirement_summary: "P0-05 requires Content-Disposition safety but does not specify the filename-input outcome for CR or LF.",
    supported_expected_policy: null,
    supported_expected_category: "content_disposition_header_safety_question",
    authority_status: AUTHORITY_STATUS.OUTCOME_NOT_FULLY_SPECIFIED,
  }),
  "THREAT_MODEL.T2.MALICIOUS_FILENAME_PATH_TRAVERSAL": Object.freeze({
    source_document: "Threat Model",
    section_or_validator_key: "T2 malicious filename path traversal",
    requirement_summary: "The active threat model identifies malicious filename path traversal as an adverse input class.",
    supported_expected_policy: "block",
    supported_expected_category: "path_traversal",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "EXECPLAN.P0_05.UNSPECIFIED_PUNCTUATION_SPACING": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: application-generated safe filename",
    requirement_summary: "The safe-filename requirement does not fully specify acceptance of spaces or punctuation in caller-provided names.",
    supported_expected_policy: null,
    supported_expected_category: "punctuation_spacing_question",
    authority_status: AUTHORITY_STATUS.OUTCOME_NOT_FULLY_SPECIFIED,
  }),
  "EXECPLAN.P0_05.UNSPECIFIED_EXTENSION_PATTERN": Object.freeze({
    source_document: "KAI_Sprint2_P0_Final_Recovery_and_Implementation_Plan_v0.3.5.md",
    section_or_validator_key: "P0-05 Pre-upload validation: extension/MIME/signature agreement",
    requirement_summary: "The extension-agreement requirement does not classify every multiple-extension or suffix pattern as dangerous.",
    supported_expected_policy: null,
    supported_expected_category: "extension_pattern_question",
    authority_status: AUTHORITY_STATUS.OUTCOME_NOT_FULLY_SPECIFIED,
  }),
});

export const FILENAME_FIXTURES = Object.freeze([
  Object.freeze({
    fixture_id: "FN-P0-05A-001-ALLOW-ASCII-BASENAME",
    control_family: "filename",
    input_kind: "safe_filename",
    input_representation: "ASCII basename report.csv",
    actual_input: "report.csv",
    synthetic_provenance: "synthetic literal created for P0-05A corpus; no client, person, credential, host, bucket, or storage path source",
    decision_status: "contract_grounded",
    expected_policy: "allow",
    expected_category: "application_generated_safe_filename",
    authority_reference: "EXECPLAN.P0_05.APPLICATION_GENERATED_SAFE_FILENAME",
    rationale: "Simple generated ASCII basename with a supported extension exercises the safe-filename allow provision only.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-002-BLOCK-DOTDOT-SLASH",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "../report.csv with parent-directory traversal sequence",
    actual_input: "../report.csv",
    synthetic_provenance: "synthetic traversal literal; no real path or client storage source",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "path_traversal",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.PATH_TRAVERSAL",
    rationale: "The asserted block outcome is controlled by the path-traversal provision, not by current detector behavior.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-003-BLOCK-DOTDOT-BACKSLASH",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "..\\\\report.csv with parent-directory backslash traversal sequence",
    actual_input: "..\\report.csv",
    synthetic_provenance: "synthetic traversal literal; no real path or client storage source",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "path_traversal",
    authority_reference: "THREAT_MODEL.T2.MALICIOUS_FILENAME_PATH_TRAVERSAL",
    rationale: "Backslash parent-directory traversal is represented under the malicious filename path-traversal threat class.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-004-BLOCK-SLASH-SEPARATOR",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "folder/report.csv with U+002F slash separator",
    actual_input: "folder/report.csv",
    synthetic_provenance: "synthetic separator literal; no real directory source",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "path_separator",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.SLASH_BACKSLASH",
    rationale: "The path-separator provision supports blocking a slash-delimited caller path.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-005-BLOCK-BACKSLASH-SEPARATOR",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "folder\\\\report.csv with U+005C backslash separator",
    actual_input: "folder\\report.csv",
    synthetic_provenance: "synthetic separator literal; no real directory source",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "path_separator",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.SLASH_BACKSLASH",
    rationale: "The path-separator provision supports blocking a backslash-delimited caller path.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-006-BLOCK-NUL",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report\\u0000.csv with exact invisible code point U+0000",
    actual_input: "report\u0000.csv",
    synthetic_provenance: "synthetic control-character literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "control_character",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.CONTROL_CHARACTERS",
    rationale: "The control-character provision explicitly covers NUL.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-007-BLOCK-C0-US",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report\\u001F.csv with exact invisible code point U+001F INFORMATION SEPARATOR ONE",
    actual_input: "report\u001F.csv",
    synthetic_provenance: "synthetic C0 control-character literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "control_character",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.CONTROL_CHARACTERS",
    rationale: "The control-character provision covers representative C0 controls.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-008-BLOCK-C1-NEL",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report\\u0085.csv with exact invisible code point U+0085 NEXT LINE",
    actual_input: "report\u0085.csv",
    synthetic_provenance: "synthetic C1 control-character literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "control_character",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.CONTROL_CHARACTERS",
    rationale: "The control-character provision covers representative C1 controls.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-009-BLOCK-BIDI-RLO",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report\\u202Ecod.exe with exact invisible code point U+202E RIGHT-TO-LEFT OVERRIDE",
    actual_input: "report\u202Ecod.exe",
    synthetic_provenance: "synthetic Unicode bidi-control literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "bidi_control",
    authority_reference: "EXECPLAN.P0_05.BIDI_REJECTION",
    rationale: "The P0-05 bidi-rejection requirement supports blocking the explicit RLO control.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-010-BLOCK-EMPTY",
    control_family: "filename",
    input_kind: "safe_filename",
    input_representation: "empty string",
    actual_input: "",
    synthetic_provenance: "synthetic empty filename literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "empty_sanitized_filename",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.EMPTY_SANITIZED_FILENAME",
    rationale: "The safe_filename length floor provides the controlling block outcome for an empty filename.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  ...["CON", "PRN", "AUX", "NUL", "COM1", "LPT1"].map((name, index) => Object.freeze({
    fixture_id: `FN-P0-05A-01${index + 1}-BLOCK-RESERVED-${name}`,
    control_family: "filename",
    input_kind: "safe_filename",
    input_representation: `reserved device-name basename ${name}`,
    actual_input: name,
    synthetic_provenance: "synthetic reserved device-name literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "reserved_device_name",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.RESERVED_DEVICE_NAMES",
    rationale: "The reserved-name provision supports blocking this canonical reserved device-name basename.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  })),
  Object.freeze({
    fixture_id: "FN-P0-05A-017-BLOCK-EXE-MISMATCH",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report.csv.exe with final prohibited executable extension .exe",
    actual_input: "report.csv.exe",
    synthetic_provenance: "synthetic dangerous-extension mismatch literal",
    decision_status: "contract_grounded",
    expected_policy: "block",
    expected_category: "dangerous_extension_mismatch",
    authority_reference: "BACKEND_CONTRACT.VAL_STO_004.DANGEROUS_EXTENSION_MISMATCH",
    rationale: "The dangerous-extension mismatch provision supports this exact executable-ending case without generalizing all multiple extensions.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-018-OWNER-UNICODE-NFD",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "cafe\\u0301.csv with decomposed U+0065 U+0301 sequence",
    actual_input: "cafe\u0301.csv",
    synthetic_provenance: "synthetic decomposed Unicode literal",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "unicode_normalization_question",
    authority_reference: "EXECPLAN.P0_05.UNICODE_NORMALIZATION",
    rationale: "The source requires normalization but does not decide normalize-and-accept versus reject.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-019-OWNER-SPACE",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report draft.csv with U+0020 space",
    actual_input: "report draft.csv",
    synthetic_provenance: "synthetic spacing literal",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "punctuation_spacing_question",
    authority_reference: "EXECPLAN.P0_05.UNSPECIFIED_PUNCTUATION_SPACING",
    rationale: "The controlling safe-filename source does not expressly decide caller-provided spaces.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-020-OWNER-PUNCTUATION",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report+draft.csv with U+002B plus sign",
    actual_input: "report+draft.csv",
    synthetic_provenance: "synthetic punctuation literal",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "punctuation_spacing_question",
    authority_reference: "EXECPLAN.P0_05.UNSPECIFIED_PUNCTUATION_SPACING",
    rationale: "The controlling safe-filename source does not expressly decide every punctuation character.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-021-OWNER-CRLF",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report\\r\\n.csv with exact invisible code points U+000D U+000A",
    actual_input: "report\r\n.csv",
    synthetic_provenance: "synthetic CRLF filename literal",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "content_disposition_header_safety_question",
    authority_reference: "EXECPLAN.P0_05.CONTENT_DISPOSITION_SAFETY",
    rationale: "Content-Disposition safety is required, but the source does not define the filename-input outcome or serialization rule.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-022-OWNER-DRIVE-STYLE",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "C:report.csv drive-style name without slash or backslash separator",
    actual_input: "C:report.csv",
    synthetic_provenance: "synthetic drive-style filename literal; no real local path source",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "drive_path_question",
    authority_reference: "EXECPLAN.P0_05.PATH_SEPARATOR_REJECTION",
    rationale: "Path rejection is required, but drive-style names without an explicit separator need an owner decision.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-023-OWNER-RESERVED-EXTENSION",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "con.txt lower-case reserved-name variant with extension",
    actual_input: "con.txt",
    synthetic_provenance: "synthetic reserved-name variant literal",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "reserved_name_variant_question",
    authority_reference: "EXECPLAN.P0_05.RESERVED_NAME_REJECTION",
    rationale: "Reserved-name rejection is required, but casing and extension semantics are not pinned by this corpus authority map.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
  Object.freeze({
    fixture_id: "FN-P0-05A-024-OWNER-UNCLASSIFIED-EXTENSION",
    control_family: "filename",
    input_kind: "original_filename",
    input_representation: "report.csv.backup with unclassified final suffix .backup",
    actual_input: "report.csv.backup",
    synthetic_provenance: "synthetic unclassified extension-pattern literal",
    decision_status: "owner_decision_required",
    expected_policy: null,
    expected_category: "extension_pattern_question",
    authority_reference: "EXECPLAN.P0_05.UNSPECIFIED_EXTENSION_PATTERN",
    rationale: "The source does not classify this suffix as a dangerous mismatch.",
    contains_client_data: false,
    contains_pii: false,
    contains_secret: false,
    corpus_status: "corpus_only",
  }),
]);

export function getContractGroundedFilenameFixtureExpectations() {
  return FILENAME_FIXTURES
    .filter((fixture) => fixture.decision_status === "contract_grounded")
    .map((fixture) => Object.freeze({
      fixture_id: fixture.fixture_id,
      actual_input: fixture.actual_input,
      expected_policy: fixture.expected_policy,
      expected_category: fixture.expected_category,
      authority_reference: fixture.authority_reference,
    }));
}
