const AUTHORITY_STATUS = Object.freeze({
  CONTRACT_GROUNDED: "contract_grounded",
});

const APPLIES_TO_TXT_MD = Object.freeze(["txt", "md"]);

export const TXT_MD_BYTE_FIXTURE_POLICIES = Object.freeze(["allow", "block"]);

export const TXT_MD_BYTE_FIXTURE_CATEGORIES = Object.freeze([
  "encoding_gate_pass",
  "invalid_utf8",
  "unsupported_bom_encoding",
  "nul_rejection",
  "prohibited_control",
  "lone_cr",
]);

export const TXT_MD_BYTE_FIXTURE_CORPUS_STATUSES = Object.freeze(["corpus_only"]);

export const TXT_MD_BYTE_FIXTURE_AUTHORITY_MAP = Object.freeze({
  "OWNER_DECISION.P0_05C.STRICT_UTF8_ONLY": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C TXT/MD encoding and deterministic binary-content boundary",
    requirement_summary: "TXT and MD byte content is evaluated as strict UTF-8 at the narrow P0 byte gate.",
    supported_expected_policy: "allow",
    supported_expected_category: "encoding_gate_pass",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.UTF8_BOM_ALLOWED": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C UTF-8 BOM allowed",
    requirement_summary: "A single leading EF BB BF sequence may be treated as the optional UTF-8 BOM.",
    supported_expected_policy: "allow",
    supported_expected_category: "encoding_gate_pass",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.UNSUPPORTED_BOM_REJECTION": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C unsupported BOM rejection",
    requirement_summary: "Unsupported BOM encodings are rejected rather than transcoded or guessed.",
    supported_expected_policy: "block",
    supported_expected_category: "unsupported_bom_encoding",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.INVALID_UTF8_REJECTION": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C invalid UTF-8 rejection",
    requirement_summary: "Invalid UTF-8 byte sequences are rejected and are proved with fatal UTF-8 decoding.",
    supported_expected_policy: "block",
    supported_expected_category: "invalid_utf8",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.NUL_REJECTION": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C NUL rejection",
    requirement_summary: "NUL is rejected by the deterministic binary-content gate.",
    supported_expected_policy: "block",
    supported_expected_category: "nul_rejection",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.PROHIBITED_CONTROL_REJECTION": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C prohibited control rejection",
    requirement_summary: "Prohibited C0 controls, DEL, and C1 controls are rejected while TAB, LF, and CRLF remain permitted cases.",
    supported_expected_policy: "block",
    supported_expected_category: "prohibited_control",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.LONE_CR_REJECTION": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C lone CR rejection",
    requirement_summary: "A CR is rejected unless it is immediately followed by LF; LF and CRLF are accepted without normalization.",
    supported_expected_policy: "block",
    supported_expected_category: "lone_cr",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.EMPTY_CONTENT_ENCODING_GATE_PASS": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C empty content encoding-gate pass",
    requirement_summary: "Empty TXT or MD bytes pass only the strict UTF-8 and deterministic binary-content gate.",
    supported_expected_policy: "allow",
    supported_expected_category: "encoding_gate_pass",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.INSTRUCTION_TEXT_IS_INERT_DATA": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C instruction text is inert data",
    requirement_summary: "Instruction-like TXT or MD text is inert untrusted data at this byte gate and is not executed or interpreted.",
    supported_expected_policy: "allow",
    supported_expected_category: "encoding_gate_pass",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
  "OWNER_DECISION.P0_05C.NONLEADING_UFEFF_ALLOWED_AS_TEXT": Object.freeze({
    source_document: "Backend/kai/contracts/KAI_SPRINT2_P0_REPOSITORY_CONTRACT.md",
    section_or_decision_key: "P0-05C non-leading U+FEFF allowed as text",
    requirement_summary: "Non-leading U+FEFF, including the second EF BB BF after the optional leading BOM, is retained ordinary text at this narrow gate.",
    supported_expected_policy: "allow",
    supported_expected_category: "encoding_gate_pass",
    authority_status: AUTHORITY_STATUS.CONTRACT_GROUNDED,
  }),
});

function txtMdFixture({
  fixture_id,
  description,
  bytes_hex,
  declared_utf8_valid,
  expected_policy,
  expected_category,
  authority,
  scope_note,
  utf8_validity_basis,
  byte_case_family,
}) {
  const normalizedHex = bytes_hex.replace(/\s+/g, " ").trim();
  const byteLength = normalizedHex === "" ? 0 : normalizedHex.split(" ").length;
  return Object.freeze({
    fixture_id,
    description,
    applies_to: APPLIES_TO_TXT_MD,
    bytes_hex: normalizedHex,
    byte_length: byteLength,
    declared_utf8_valid,
    expected_policy,
    expected_category,
    authority,
    scope_note,
    utf8_validity_basis,
    byte_case_family,
    synthetic_provenance: "synthetic literal created for the P0-05D TXT/MD byte-fixture corpus; generated locally and not sourced from client data, deployed data, external services, credentials, or real documents",
    corpus_status: "corpus_only",
    usable_document_claim: false,
    source_eligibility_claim: false,
    production_detector_claim: false,
  });
}

export const TXT_MD_BYTE_FIXTURES = Object.freeze([
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-001-ALLOW-ASCII",
    description: "Ordinary ASCII text accepted only as a strict UTF-8 byte-gate pass.",
    bytes_hex: "70 6C 61 69 6E 20 61 73 63 69 69 20 74 65 78 74",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.STRICT_UTF8_ONLY",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "strict_utf8_basic",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-002-ALLOW-MULTIBYTE",
    description: "Valid multibyte UTF-8 text accepted only as a strict UTF-8 byte-gate pass.",
    bytes_hex: "63 61 66 C3 A9 20 E2 9C 93 20 E6 9C AC",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.STRICT_UTF8_ONLY",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "strict_utf8_basic",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-003-ALLOW-LF",
    description: "LF line ending remains on the permitted side of the control boundary.",
    bytes_hex: "61 6C 70 68 61 0A 62 65 74 61",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.STRICT_UTF8_ONLY",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "permitted_control_boundary",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-004-ALLOW-CRLF",
    description: "CRLF line ending remains permitted without normalization or rewriting.",
    bytes_hex: "61 6C 70 68 61 0D 0A 62 65 74 61",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.STRICT_UTF8_ONLY",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "permitted_control_boundary",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-005-ALLOW-TAB",
    description: "TAB remains on the permitted side of the C0 control boundary.",
    bytes_hex: "6B 65 79 09 76 61 6C 75 65",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.STRICT_UTF8_ONLY",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "permitted_control_boundary",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-006-ALLOW-EMPTY",
    description: "Empty byte content passes only the encoding and deterministic binary-content gate.",
    bytes_hex: "",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.EMPTY_CONTENT_ENCODING_GATE_PASS",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "empty_content",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-007-ALLOW-INSTRUCTION-LIKE-TEXT",
    description: "Instruction-like text remains inert untrusted data and passes only the byte gate.",
    bytes_hex: "49 67 6E 6F 72 65 20 61 6C 6C 20 70 72 69 6F 72 20 72 75 6C 65 73 2E",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.INSTRUCTION_TEXT_IS_INERT_DATA",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "instruction_like_inert_data",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-008-ALLOW-LEADING-UTF8-BOM-TEXT",
    description: "One leading EF BB BF followed by valid UTF-8 text is the optional UTF-8 BOM case.",
    bytes_hex: "EF BB BF 74 65 78 74",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.UTF8_BOM_ALLOWED",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "leading_utf8_bom",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-009-ALLOW-LEADING-UTF8-BOM-ONLY",
    description: "One leading EF BB BF with no following content remains limited to the empty-content byte-gate scope.",
    bytes_hex: "EF BB BF",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.UTF8_BOM_ALLOWED",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "leading_utf8_bom",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-010-ALLOW-NONLEADING-UFEFF",
    description: "EF BB BF after byte offset zero decodes and remains ordinary U+FEFF text.",
    bytes_hex: "61 EF BB BF 62",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.NONLEADING_UFEFF_ALLOWED_AS_TEXT",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "nonleading_ufeff",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-011-ALLOW-TWO-INITIAL-EFBBBF",
    description: "Two initial EF BB BF sequences retain the second sequence as ordinary U+FEFF after the single optional leading BOM.",
    bytes_hex: "EF BB BF EF BB BF 62",
    declared_utf8_valid: true,
    expected_policy: "allow",
    expected_category: "encoding_gate_pass",
    authority: "OWNER_DECISION.P0_05C.NONLEADING_UFEFF_ALLOWED_AS_TEXT",
    scope_note: "encoding_gate_pass_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "two_initial_efbbbf",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-012-BLOCK-ISOLATED-CONTINUATION",
    description: "Raw isolated UTF-8 continuation byte is invalid UTF-8 and is rejected.",
    bytes_hex: "80",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "invalid_utf8",
    authority: "OWNER_DECISION.P0_05C.INVALID_UTF8_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "invalid_utf8_isolated_continuation",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-013-BLOCK-TRUNCATED-MULTIBYTE",
    description: "Raw truncated UTF-8 multibyte sequence is invalid UTF-8 and is rejected.",
    bytes_hex: "E2 82",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "invalid_utf8",
    authority: "OWNER_DECISION.P0_05C.INVALID_UTF8_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "invalid_utf8_truncated_sequence",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-014-BLOCK-INVALID-LEADING-BYTE",
    description: "Raw invalid UTF-8 leading byte is invalid UTF-8 and is rejected.",
    bytes_hex: "FF",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "invalid_utf8",
    authority: "OWNER_DECISION.P0_05C.INVALID_UTF8_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "invalid_utf8_invalid_leading_byte",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-015-BLOCK-OVERLONG",
    description: "Raw overlong UTF-8 sequence is invalid UTF-8 and is rejected.",
    bytes_hex: "C0 AF",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "invalid_utf8",
    authority: "OWNER_DECISION.P0_05C.INVALID_UTF8_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "invalid_utf8_overlong",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-016-BLOCK-SURROGATE-ENCODED",
    description: "Raw UTF-8 sequence encoding a surrogate code point is invalid UTF-8 and is rejected.",
    bytes_hex: "ED A0 80",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "invalid_utf8",
    authority: "OWNER_DECISION.P0_05C.INVALID_UTF8_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "invalid_utf8_surrogate_encoded",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-017-BLOCK-UTF16-LE-BOM",
    description: "Raw UTF-16 little-endian BOM bytes are an unsupported BOM encoding and are rejected.",
    bytes_hex: "FF FE 61 00",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "unsupported_bom_encoding",
    authority: "OWNER_DECISION.P0_05C.UNSUPPORTED_BOM_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "unsupported_bom_utf16_le",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-018-BLOCK-UTF16-BE-BOM",
    description: "Raw UTF-16 big-endian BOM bytes are an unsupported BOM encoding and are rejected.",
    bytes_hex: "FE FF 00 61",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "unsupported_bom_encoding",
    authority: "OWNER_DECISION.P0_05C.UNSUPPORTED_BOM_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "unsupported_bom_utf16_be",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-019-BLOCK-UTF32-LE-BOM",
    description: "Raw UTF-32 little-endian BOM bytes are an unsupported BOM encoding and are rejected.",
    bytes_hex: "FF FE 00 00 61 00 00 00",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "unsupported_bom_encoding",
    authority: "OWNER_DECISION.P0_05C.UNSUPPORTED_BOM_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "unsupported_bom_utf32_le",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-020-BLOCK-UTF32-BE-BOM",
    description: "Raw UTF-32 big-endian BOM bytes are an unsupported BOM encoding and are rejected.",
    bytes_hex: "00 00 FE FF 00 00 00 61",
    declared_utf8_valid: false,
    expected_policy: "block",
    expected_category: "unsupported_bom_encoding",
    authority: "OWNER_DECISION.P0_05C.UNSUPPORTED_BOM_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_throw",
    byte_case_family: "unsupported_bom_utf32_be",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-021-BLOCK-NUL",
    description: "NUL is valid UTF-8 but policy-blocked by the deterministic binary-content gate.",
    bytes_hex: "61 00 62",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "nul_rejection",
    authority: "OWNER_DECISION.P0_05C.NUL_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "prohibited_control_nul",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-022-BLOCK-PROHIBITED-C0-US",
    description: "U+001F INFORMATION SEPARATOR ONE is valid UTF-8 but policy-blocked as a prohibited C0 control.",
    bytes_hex: "61 1F 62",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "prohibited_control",
    authority: "OWNER_DECISION.P0_05C.PROHIBITED_CONTROL_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "prohibited_control_c0",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-023-BLOCK-DEL",
    description: "DEL is valid UTF-8 but policy-blocked as a prohibited control.",
    bytes_hex: "61 7F 62",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "prohibited_control",
    authority: "OWNER_DECISION.P0_05C.PROHIBITED_CONTROL_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "prohibited_control_del",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-024-BLOCK-C1-NEL",
    description: "U+0085 NEXT LINE is valid UTF-8 but policy-blocked as a prohibited C1 control.",
    bytes_hex: "61 C2 85 62",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "prohibited_control",
    authority: "OWNER_DECISION.P0_05C.PROHIBITED_CONTROL_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "prohibited_control_c1",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-025-BLOCK-LONE-CR-BEGIN",
    description: "Lone CR at the beginning is valid UTF-8 but rejected unless immediately followed by LF.",
    bytes_hex: "0D 61 62 63",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "lone_cr",
    authority: "OWNER_DECISION.P0_05C.LONE_CR_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "lone_cr_begin",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-026-BLOCK-LONE-CR-MIDDLE",
    description: "Lone CR between valid characters is valid UTF-8 but rejected unless immediately followed by LF.",
    bytes_hex: "61 0D 62",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "lone_cr",
    authority: "OWNER_DECISION.P0_05C.LONE_CR_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "lone_cr_middle",
  }),
  txtMdFixture({
    fixture_id: "TXTMD-P0-05D-027-BLOCK-LONE-CR-END",
    description: "Lone CR at the end is valid UTF-8 but rejected unless immediately followed by LF.",
    bytes_hex: "61 62 63 0D",
    declared_utf8_valid: true,
    expected_policy: "block",
    expected_category: "lone_cr",
    authority: "OWNER_DECISION.P0_05C.LONE_CR_REJECTION",
    scope_note: "encoding_binary_gate_block_only",
    utf8_validity_basis: "fatal_decoder_must_succeed",
    byte_case_family: "lone_cr_end",
  }),
]);

export function bytesFromHex(bytesHex) {
  if (bytesHex === "") return new Uint8Array();
  return Uint8Array.from(bytesHex.split(" ").map((byte) => Number.parseInt(byte, 16)));
}

export function getTxtMdByteFixtureExpectations() {
  return TXT_MD_BYTE_FIXTURES.map((fixture) => Object.freeze({
    fixture_id: fixture.fixture_id,
    applies_to: fixture.applies_to,
    bytes_hex: fixture.bytes_hex,
    declared_utf8_valid: fixture.declared_utf8_valid,
    expected_policy: fixture.expected_policy,
    expected_category: fixture.expected_category,
    authority: fixture.authority,
    scope_note: fixture.scope_note,
  }));
}
